site_name: HOYA Documentation
# Project information
site_description: Documentation for Global Finance
site_author: Nodoka Kushioka and Valerie Lim
site_url: https://valerieljx.github.io/HOYA-Documentation/

# Copyright
copyright: Copyright &copy; 2025 HOYA Surgical Optics

# Configuration
theme:
  name: material
  logo: images/hoyasurgicaloptics_logo.jpg
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: hso
      primary: hso
      accent: hso
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: hso-dark
      primary: hso-dark
      accent: hso-dark
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
- stylesheets/extra.css
- stylesheets/custom.css

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      linenums: false
      auto_title: true  
  - pymdownx.superfences
  - pymdownx.tabbed
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true

# Plugins
plugins:
  - search
  - redirects
  - awesome-pages
  - glightbox
  - git-revision-date-localized:
      type: date
  - minify:
      minify_html: true
  - pdf-export:
      enabled_if_env: ENABLE_PDF_EXPORT

# Navigation structure
nav:
  - Introduction: introduction.md
  - Terminology:
    - General Terminology:
        - Programming Languages: docs/general_terminology/languages.md
        - Big Data: docs/general_terminology/big_data.md
        - Data Engineering: docs/general_terminology/data_engineering.md
        - Data Analytics: docs/general_terminology/data_analytics.md
        - Data Visualization: docs/general_terminology/data_viz.md
        - Data Science: docs/general_terminology/data_science.md
    - Fabric Terminology:
        - Get Data: docs/terminology/get_data.md
        - Store Data: docs/terminology/store_data.md
        - Prepare Data: docs/terminology/prepare_data.md
        - Analyze and Train Data: docs/terminology/analyze_train_data.md
        - OneLake: docs/terminology/onelake.md
    - Finance Terminology:
        - Financial and Accounting Terms: docs/finance_terms/finance_accounting_terms.md
        - Finance KPIs: docs/finance_terms/finance_kpi.md
    - Calendar Terminology:
        - Calendar Systems and Accounting Period: docs/general_terminology/calendar_types.md
  - Using Fabric Tools:
    - Lakehouse: docs/fabric_tools/lakehouse.md
    - SQL Analytics Endpoint: docs/fabric_tools/sql_endpoint.md
    - Notebook: docs/fabric_tools/notebook.md
    - Semantic Model: docs/fabric_tools/semantic_model.md
    - Warehouse: docs/fabric_tools/warehouse.md
    - SQL Database: docs/fabric_tools/sql_database.md
    - Dataflow: docs/fabric_tools/dataflow.md
    - Pipelines: docs/fabric_tools/pipelines.md
    - ML Model: docs/fabric_tools/ml_model.md
    - Reports: docs/fabric_tools/reports.md
  - Programming Tools:
    - Git: docs/programming_tools/git.md
  - Power BI:
    - Best Dashboard Design Practices: docs/power_bi/best_design_pracs.md
    - VertiPaq Engine: docs/power_bi/vertipaq.md
  - Architecture:
    - Star Schema Design: docs/architecture/star_schema.md
    - Dimension Design: docs/architecture/dimension_design.md
    - Fact Design: docs/architecture/fact_design.md
    - Snowflake Schema: docs/architecture/snowflake.md
    - Data Model Relationships: docs/architecture/relationships.md
    - Naming Convention: docs/architecture/naming_convention.md
  - Automation:
    - STRAVIS Automation: docs/automation/stravis_automation.md
    - SAP Automation: docs/automation/sap_automation.md
  - Inforiver: docs/inforiver.md
  - References: docs/references.md

# Additional settings
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/valerieljx